name: Update Chrome Extension

on:
    push:
        branches:
            - "38-cicd"

jobs:
    build-chrome-extension:
        name: Build Chrome extension artifact
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  token: ${{ secrets.ACTION_TOKEN }}

            - name: Build and Archive
              run: |
                  yarn && yarn build:prod
                  zip -r chrome-extension-${{ github.event.pull_request.head.sha }}.zip build

            - name: Archive chrome-extension artifact
              uses: actions/upload-artifact@v2
              with:
                  name: chrome-extension-${{ github.event.pull_request.head.sha }}
                  path: chrome-extension-${{ github.event.pull_request.head.sha }}.zip

    upload-extension:
        name: Upload extension
        runs-on: ubuntu-latest
        needs: build-chrome-extension
        env:
            EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Download bundle artifact
              uses: actions/download-artifact@v3
              with:
                  name: chrome-extension-${{ github.event.pull_request.head.sha }}

            - name: Install webstore cli
              run: |
                  npm install -g chrome-webstore-upload-cli

            - name: Upload step
              run: |-
                  chrome-webstore-upload upload \
                    --source chrome-extension-${{ github.event.pull_request.head.sha }}.zip \
                    --extension-id ${{ env.EXTENSION_ID }} \
                    --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} \
                    --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} \
                    --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
