# [Reference] https://github.com/fregante/chrome-webstore-upload-keys?tab=readme-ov-file
# [Reference] https://jam.dev/blog/automating-chrome-extension-publishing/
name: Update Chrome Extension

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version number"
                required: true
                default: "1.0.0"

jobs:
    build-chrome-extension:
        name: Build Chrome extension artifact
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  token: ${{ secrets.ACTION_TOKEN }}

            - name: Build and Archive
              run: |
                  yarn && yarn build:prod
                  zip -r chrome-extension-${{ github.event.inputs.version }}.zip build
              env:
                  VERSION: ${{ github.event.inputs.version }}

            - name: Archive chrome-extension artifact
              uses: actions/upload-artifact@v2
              with:
                  name: chrome-extension-${{ github.event.inputs.version }}
                  path: chrome-extension-${{ github.event.inputs.version }}.zip

    upload-extension:
        name: Upload extension
        runs-on: ubuntu-latest
        needs: build-chrome-extension
        steps:
            - uses: actions/download-artifact@v4
            - run: npx chrome-webstore-upload-cli@3
              working-directory: artifact
              env:
                  EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
                  CLIENT_ID: ${{ secrets.CI_GOOGLE_CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CI_GOOGLE_CLIENT_SECRET }}
                  REFRESH_TOKEN: ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}

    commit-and-tag:
        name: Commit manifest.json and push version tag
        runs-on: ubuntu-latest
        needs: upload-extension
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.ACTION_TOKEN }}

            - name: Configure Git
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

            - name: Commit updated manifest.json
              run: |
                  git add public/manifest.json
                  git commit -m "Update manifest.json for version ${{ github.event.inputs.version }}"

            - name: Create and push tag
              run: |
                  git tag -a v${{ github.event.inputs.version }} -m "Release version ${{ github.event.inputs.version }}"
                  git push origin v${{ github.event.inputs.version }}
                  git push origin main  # Push the commit to the main branch
